### ISSUE TITLE
Themes don't work with clumping

### ISSUE THREAD

**Issue by armartin** [veera-dr/ggman#1]
When plotting via ggman, new themes (e.g. theme_bw) cannot be applied when using clumping. As an example from the toy data, the first 3 plots generate correctly, but the 4th does not produce a plot:

```
library(ggman)

p1 <- ggman(toy.gwas, relative.positions = TRUE)

p2 <- ggman(toy.gwas, relative.positions = TRUE) +
  theme_bw()

toy.clumps <- ggmanClumps(toy.clumped, index.snp.column = "SNP", clumps.column = "SP2", group.column = "group", label.column = "label") 

p3 <- ggman(toy.gwas,clumps = toy.clumps, relative.positions = TRUE, pointSize = 0.5)

p4 <- ggman(toy.gwas,clumps = toy.clumps, relative.positions = TRUE, pointSize = 0.5) +
  theme_bw()
```

**Comment by drveera** [comment]
Hi Alicia,
Thanks for trying the package. I actually tweaked the clumping part little bit recently for some other purpose. I will make updates soon. But for now the output of ggman with clumps enabled is a list (not ggplot) and the plot object is the first item in the list. So,

`p1 <- ggman(toy.gwas,clumps = toy.clumps, relative.positions = TRUE, pointSize = 0.5)`
`p2 <- p1[[1]] + theme_bw() #or any ggplot layer`

**Comment by armartin** [comment]
Hi Veera, thanks so much for your quick response. That resolves my issue!
