### ISSUE TITLE
Genome wide significance line

### ISSUE THREAD

**Issue by papeilas** [veera-dr/ggman#2]
Hi Veera,
Nice package!
One suggestion is that your genome wide significance red line should be around 7.3 and not 8...
–log10(p) < 7.3 corresponds to p > 5x10-8 which I believe is more relevant!
You can also let users choose their suggestive lines as an option in the future.
Cheers,
Chris

**Comment by drveera** [comment]
Hi Chris,
 You are right. I was just lazy to change that :) I will change it now. But you can always provide your own threshold, using sigLine= argument. Also, you can additional horizontal lines by adding ggplot layers, for example

```
p1 <- ggman(...)
p1 + geom_hline(yintercept = 7.3)
```
there is no limit, you can stack up how many layers ever you want

Regards
Veera
