### ISSUE TITLE
ggmanZoom highlights

### ISSUE THREAD

**Issue by santaci** [veera-dr/ggman#4]
Hello, I've been using this package and have managed to make most of the plots using my own data with the exception of the highlighting when zoom into a specific chromosome. It seems that ggmanZoom does not recognize the arguments "highlight.group" or "legend.title". 

The documentation suggests that the plot created using ggman should contain information from the original dataset used to create it (the example of the "genes" column) - would this only work if the plot was created for log-transformed p-values? I've been making my plots for other values (not p-values).

**Comment by santaci** [comment]
An alternative that I found was to do the following, with geom_point:
ggmanZoom(maybeplot, chromosome = 1) + geom_point(aes(colour=gene))

**Comment by drveera** [comment]
Hi, thanks for trying the package. ggmanZoom was changed (similar to locusZoom) and I didn't update that in the documentation. I'll try to do that sometime in future. You alternative is good and many such things can be done by adding a ggplot2 layers, so you really don't need anything special from ggman per se. Regarding using values other than P values, there is an argument called "logTransform=TRUE", you can change that to FALSE.
