### ISSUE TITLE
Labelling of Y axis

### ISSUE THREAD

**Issue by virpatel524** [veera-dr/ggman#6]
Awesome package—just wanted to know if there is any way to display a different label for the Y-axis instead of the default -log10. I figure since you have the option to specify different columns for the data points, the Y axis should reflect that. For now, I'll just edit manually, but integrated functionally would be fantastic. 

Appreciate your work here!

**Comment by drveera** [comment]
Hi,

Thank you. You can change the y axis label, using argument `ylabel="whatever"`. If you meant y axis values, then you can turn off the log conversion using argument `logTransform=FALSE` and use any values for Y axis, for example odds ratio, beta etc.

**Comment by virpatel524** [comment]
Thanks so much! Did not notice that in the documentation but will do!
