### ISSUE TITLE
error when Zoom in to a specific region of a chromosome

### ISSUE THREAD

**Issue by LiangMa2017** [veera-dr/ggman#8]
Hello, nice tool for Manhattan plot. Zoom in chromosome 1 is ok to be plotting. But the toy showed error when zooming in a specific region. Do you have any suggestions to solve this? I pasted the command I used and the output below. Thanks!

> p1 <- ggman (toy.gwas, snp = "snp", bp = "bp", chrom = "chrom", pvalue = "pvalue", relative.positions = TRUE)
> ggmanZoom (p1, chromosome = 1)
> ggmanZoom (p1, chromosome = 1, start.position = 215388741, end.position = 238580695)
Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ, clusterExport, clusterMap, parApply, parCapply,
    parLapply, parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, cbind, colMeans, colnames, colSums, do.call, duplicated, eval,
    evalq, Filter, Find, get, grep, grepl, intersect, is.unsorted, lapply, lengths, Map, mapply, match,
    mget, order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank, rbind, Reduce, rowMeans, rownames,
    rowSums, sapply, setdiff, sort, table, tapply, union, unique, unsplit, which, which.max, which.min

Loading required package: S4Vectors

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges
Loading required package: GenomeInfoDb
Error in normArgTrack(track, trackids) : Unknown track: refGene

**Comment by drveera** [comment]
Hi,

Please use gene.tracks=FALSE, then it should be okay. It queries UCSC to show gene tracks by default thats why you get that error.  I didn't update that querying part of the code for quiet sometime. Not sure If i'll, since it can be easily done in Locus Zoom. 

Veera

**Comment by LiangMa2017** [comment]
Hi Veera,
Thank you so much for your suggestions. It works when adding gene.tracks=FALSE. 
I don't know why I got this error, just try to replicate the example in the manual.
Cheers!
>p1 <- ggman (toy.gwas, snp = "snp", bp = "bp", chrom = "chrom", pvalue = "pvalue",
             relative.positions = TRUE)
>ggmanZoom (p1, chromosome = 1)
>ggmanZoom (p1, chromosome = 1, start.position = 215388741, end.position = 238580695, gene.tracks=FALSE)
